#----------------------------------------------------------------------
# This file was generated by /usr/lib/python2.7/dist-packages/wx-3.0-gtk2/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

#----------------------------------------------------------------------
about_item = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAA3NCSVQICAjb4U/gAAAACXBI"
    "WXMAAA3XAAAN1wFCKJt4AAAAGXRFWHRTb2Z0d2FyZQB3d3cuaW5rc2NhcGUub3Jnm+48GgAA"
    "AS9QTFRF////xpwAxKIAwaIAx6IAxKAAw50Aw6IAw58AwqAAxaAAxaAAxqECxqMCxqMDx6QD"
    "xKMDxqMExqIAxqIBxqIByKMEyKMFx6MDx6MFxaMBxKEBxKECw6AByKkMy6kOyKYKyacLzKwW"
    "zK4ZxqIDxqQGx6QEyKcLyKcMy6wczK0hxaIExqQIxKAB59V459V7z7Il0LIn0LAX1r1G3MVE"
    "38pV4tBZ49Jg6dyM6d2L18Am2cAp3shC4s9X4tA85NE959VE6NdT6Nlj6dhP6dpp6dty6ttq"
    "6txv69tY7N1i7N9v7OB87eB27+Fv7+Jz7+J37+OA8OWW8OaS8eR38eR48eeW8ueP9OmI9Oue"
    "9Ous9e2s9uqN9uuO+fLA+vGi+vTH+vbY+vff+/Kr+/fc/PjW/fzwau+AmgAAADl0Uk5TABIe"
    "ISkrLzdAQ0tToKCgoLKys7PIy8vMzNLr6+/z8/T09fX29vb29vb29/f6+/v8/P39/f39/f7+"
    "B/bSawAAAJtJREFUGBlVwYMOwwAABcC3Dp1t27Zt297+/xu2LE3W3gE/hJkAgyqpBB0ZuPtJ"
    "0Mjz75wCf0TotnsGCVA4ElfkfHxFXTIOvlhSX2p+2F4e133aK2YBpnirW+8tT6fVdNGOGdng"
    "6p2l4ag/nmzWZYeOiy+RwZYZNGdZu0EEisDdqHY8Avypi5WCGjRCa80iBJ02oQEDL8wDEx+U"
    "D8upFKHq33LQAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
open_item = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAAlw"
    "SFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoA"
    "AAAOdEVYdFRpdGxlAEZvbGRlcnMhVKpgQQAAABd0RVh0QXV0aG9yAExhcG8gQ2FsYW1hbmRy"
    "ZWnfkRoqAAAAKXRFWHREZXNjcmlwdGlvbgBCYXNlZCBvZiBKYWt1YiBTdGVpbmVyIGRlc2ln"
    "bqCEBXMAAAIXSURBVDiNpZLNS5RRFIefe+eKX31ooEYgtclFBWHfUESfRH9AhESLjBZBEESt"
    "yoVkbfsDXFYE7iMiCIQWhZVhRISQYwT2MWozve87zrz3ntPCyXFKbdGBAxfOPQ+/8zvHqCr/"
    "Ew6gv/+wI5t1iwtb4t3pqaGh8C+Audm745rN2AFrbKaqRVGVKKi/1Df45t6KgIHz3dH2Y73N"
    "QQwqARFBJBDKRT6+fpj4EB/sGxx7tewIiqlPy57x96M1hbWtbazv2tc49eHZ81sXdjozrwsW"
    "ZJo5NXrDiSpxXFhozEWByVwJncgCGNhY440xhq7OVjpWmYbp7MiAC0FIoipgMlfi/t0HOFfT"
    "txDee86c7aF1cwsSQoMLQcn/mCH1ft4+VZxzPHn6aEnA8SMnUVWKxQRRxYkocRSBMTUfd3Xv"
    "Wc43ANLUE0RxQSFN00UAC8DL0Reo/H0GRw+dwBol+BQRMFdPb0tZs8nBPOBb4rjcc4BPY4+R"
    "JQAAIgKqJHOC29DebFsa8xgrAGxtq+P7TET73otYVw+q6KIUEVQVn5YpDN/BIcF27j+HzdSh"
    "ChICSfyT3Pg7yqW5anPF4N/Z1tFJPva4fJQSzc5SKEyDmuqdaGUoVVQFFFQEFUFUmP7ymXyU"
    "4gpFL1+nJmzT6nVYazGmkpW3qCAhEEJAQsB7DxLIz0yRT7y6UtlceTsyfFtC2rTi3v4Im6lL"
    "EK7/Akz7OQ+HYUtsAAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
exit_item = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABmJLR0QA/wD/AP+gvaeTAAAB"
    "sElEQVR42qWTT0sbQRjGf5nZzO4mGmrFnnoK9lAQGrAtilAJIpRCTwXPxQ9gj8VT8eYnELzl"
    "oEhBELFioRiM4M1La8RLD2FjpDWOZhMUS5KNhyU2awwIGXgv78zzPPO8f6DLE+qQbzwUb3S6"
    "cZwcrltCa43W5xQKJ8zMfGp7ZzxEORKJYFnmvULibuJ4ehKAWq3m/zEUQgiBEBIAZSlM2wwQ"
    "NFoC2f+EjQ9viMcHqdfrbYqWrbBsFbTQVAWo61OGLnKsv39NIjHM9vYPisXif4KohZQC97wS"
    "rMH+t71gecNlFkefMzExyezsZxwnD4Bpm0gp2mvw9/QqEEeFEn3K912pVEgmk35Be2wivfYd"
    "C79PsB5FEYakcFYGID4+xFQmSyaT5vr6H/n8sQ9QEqXCQYKR3cPbxHwLOJv9idY62GevgdFK"
    "8HHu7a2N1JfvXhPsODnKZReAarWK65YAkGGJMo2Og8RUJguA53lcXl7x6+CA9E6atdV1XiZf"
    "EOuPYba0MbALhpLq6bOBau7wj7e1tcny1yWWUiuMvXtF7HEvylIYhiQkBKsLG/6cdbtM3W4z"
    "N/k4lmuNg010AAAAAElFTkSuQmCC")

#----------------------------------------------------------------------
eye_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABh0lEQVR42mNkoBAwDk4D+Pn5"
    "OXl4eCxZWVmVQfzfv3/f/fr16/EPHz58x2uAmJiYDBBXs7CwxAC5PGhqv/z582fJ69evW1++"
    "fPkEwwB1dfUcTk7ODiDzIRDf/fv37xdmZmY/IJsbiP8D8RkoW/7Hjx8VN27cmAI2AOhUNkVF"
    "xQVAxUHfv3+v+f///3kg/ePx48dHVVRUcoDyk6F2/AeKuwJpQ6BFLUAL1j148CCBUU9PbysT"
    "E5Ppu3fv/B49enRCU1NzBtDPB+7cubMCyO5kZ2cvg7ny169fM69du5YhKytrISwsvOnfv3+n"
    "GXV1dbcCbTcFBpAf0ESwAUBNKUD1IH/KIXsTZoC8vLyFoKAgxABubm6wF4ABFwT0G9gLQCfu"
    "xhJDYC8wMjIacnBwgL1w//79BLgiNTW1HC4uLlggfgViEyRDUAIRaFDFzZs3p2BEo4iIiIy4"
    "uHg1MP6xRiMwbJa8evWqFRiVmNGIDPj4+DiBXgMnJKCTQX4HJ6RPnz7hT0jkgIE3AAAWhbPm"
    "ZIjzsAAAAABJRU5ErkJggg==")

#----------------------------------------------------------------------
email_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABYUlEQVR42q3Tv0tCURTA8e/z"
    "1zMze2YUFdXg1BpEGA1G0CYK9Re0uDQ0SA0uLjaEQ0ODU4trg9W/0BxNTQX9cugHvbCwR4J2"
    "bk8Ig6iXPrjD49zzOefc+55Gh4/WDWBTlv+f+Za2MItZTGP4HPbSdEG6yLOWXMIsbQnwCLr7"
    "b8kNBQzDckYBi5jlXYyHChge8Hp+SZbsulTXI5BaU0BcgAKGCt5ew8gEuH8Yp9GEmnQaHLTf"
    "U58dzAuQt4GmbDi7gKkYuL4hKlY5hbFROflWLJVVQEyAnA1Ua9ATgqs7iM593bHkcn8CkX7p"
    "oAqhQAvIKUBuoZzFsOrgC9qVLUvGeRMkbm+sHMOQT+K6Pcb7q9y7V4C8AmYw9zMYLn972y9S"
    "6fwSPHJg0UkI9LWfRUOKrBQESEzzdLBBWHP6HQiS3MbUBno5LK+TGA87A25MGWGHI1VXJmdV"
    "lkMCIdjrys/U0fMBuRxnmaTKh98AAAAASUVORK5CYII=")
